idSubject = {
    # Sistemas
    "ACA0907": "Taller de Ética",
    "AEC0902": "Cálculo Integral",
    "ACE0903": "Álgebra Lineal",
    "ACF0905": "Ecuaciones Diferenciales",
    "AEC1034": "Fundamentos de Telecomunicaciones",
    "SCD1021": "Redes de Computadora",
    "CND2201": "Conmutación y Enrutamiento de Redes de Datos",
    "SCA1002": "Administración de Redes",
    "CND2204": "Seguridad de Redes y Cómputo en la nube",
    "ACE1058": "Química",
    "SCC1017": "Métodos Numéricos",
    "AEC1061": "Sistemas Operativos",
    "SCA1026": "Taller de Sistemas Operativos",
    "CND2202": "Ciencia de Datos",
    "CND2205": "Arquitectura Orientada a Servicios",
    "AEF1041": "Matemáticas Discretas",
    "SCD1018": "Principios Eléctricos y Aplic. Dig.",
    "SCD1013": "Estructura de Computadoras",
    "SCC1023": "Sistemas Programables",
    "SCC1019": "Programación Lógica y Funcional",
    "SCC1012": "Inteligencia Artificial",
    "AEB1055": "Programación Web",
    "AED1285": "Fundamentos de Programación",
    "AED1286": "Programación Orientada a Objetos",
    "AED1026": "Estructura de Datos",
    "SCD1027": "Tópicos Avanzados de Programación",
    "SCC1010": "Graficación",
    "AEF1031": "Fundamentos de Bases de Datos",
    "SCA1025": "Taller de Bases de Datos",
    "SCB1001": "Administración de Bases de Datos",
    "CND2203": "Taller de Desarrollo ágil de Software",
    "SCH1024": "Taller de Administración",
    "AEC1008": "Contabilidad Financiera",
    "SCF1006": "Física General",
    "SCD1015": "Lenguajes y Autómatas I",
    "SCD1016": "Lenguajes y Autómatas II",
    "ACD0908": "Desarrollo Sustentable",
    "SCC1007": "Fundamentos de Ingeniería de Software",
    "SCC1011": "Ingeniería de Software",
    "SCG1009": "Gestión de Proyectos de Software",
    "ACC0906": "Fundamentos de Investigación",
    "AEF1052": "Probabilidad y Estadística",
    "SCC1013": "Investigación de Operaciones",
    "SCD1022": "Simulación",
    "ACA0909": "Taller de Investigación I",
    "ACA0910": "Taller de Investigación II",
    "SCC1005": "Cultura Empresarial",
    # Inglés
    "LED1901": "Lengua Extranjera I",
    "LED1902": "Lengua Extranjera II",
    "LED1903": "Lengua Extranjera III",
    "LED1904": "Lengua Extranjera IV",
    "LED1905": "Lenguae Extranjera V"
}